// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sample.jsf;

import com.sample.jsf.UserBean;
import java.io.Serializable;

privileged aspect UserBean_Roo_Serializable {
    
    declare parents: UserBean implements Serializable;
    
    private static final long UserBean.serialVersionUID = 1L;
    
}
