// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sample.jsf;

import com.sample.jsf.UserBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserBean_Roo_Configurable {
    
    declare @type: UserBean: @Configurable;
    
}
